---

sudo: required

language: minimal

services:
  - docker

script:
  # Download and Run Base Test Script
  - wget -O $PWD/tests/test.sh https://raw.githubusercontent.com/ergontech-ansible-roles/role-development-toolkit/master/scripts/base-tests.sh
  - chmod +x $PWD/tests/test.sh
  - ${PWD}/tests/test.sh

  # Test Cron Files Exists
  - ls /etc
  - ls -la /etc/cron.d
  - test -f /etc/cron.d/main-job
  - test -f /etc/cron.d/test-file

  # Test Cron is running
  - /etc/init.d/cron status
