---

sudo: required
language: minimal

env:
  - distro: ubuntu1604
  - init: "/lib/systemd/systemd"
  - opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - red: '\033[0;31m'
  - green: '\033[0;32m'
  - neutral: '\033[0m'
  - container_id: $(date +%s)
  - role_dir: ${role_dir:-"$PWD"}

services:
  - docker

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'
  - 'docker run --detach --volume="$role_dir":/etc/ansible/roles/role_under_test:rw --name $container_id $opts geerlingguy/docker-$distro-ansible:latest $init'

script:
  - PWD
  - ls


#script:
#  - container_id=${mktemp)
#  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/cron:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

# Test Syntax
#  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/cron/tests/test.yml --syntax-check'
