---

sudo: required

language: minimal

services:
  - docker

before_install:
  # Set some vars
  - export container_id=$(date +%s)
  - export init="/lib/systemd/systemd"
  - export red='\033[0;31m'
  - export green='\033[0;32m'
  - export neutral='\033[0m'
  # Deal with docker
  - docker pull geerlingguy/docker-ubuntu1604-ansible:latest
  - docker run --detach -v ${PWD}:/etc/ansible/roles/cron  --name $container_id --privileged geerlingguy/docker-ubuntu1604-ansible:latest $init
  - docker ps -a


script:
  # Test Syntax
  - docker exec --tty ${container_id} env TERM=xterm ansible-playbook /etc/ansible/roles/cron/tests/test.yml --syntax-check


#script:
#  - container_id=${mktemp)
#  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/cron:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'


