---

sudo: required

language: minimal

services:
  - docker

before_script:
  # Set some vars
  - export container_id='test-role-container'

script:
  # Download and Run Base Test Script
  - wget -O $PWD/tests/test.sh https://raw.githubusercontent.com/ergontech-ansible-roles/role-development-toolkit/master/scripts/base-tests.sh
  - chmod +x $PWD/tests/test.sh
  - ${PWD}/tests/test.sh

  # Test Cron Files Exists
  - docker exec $container_id test -f /etc/cron.d/main-job
  - docker exec $container_id test -f /etc/cron.d/test-file

  # Test Cron is running
  - docker exec $container_id /etc/init.d/cron status

after_script:
  # Remove the Docker container
  - printf "Removing Docker container...\n"
  - docker rm -f $container_id