---

# Loop over all cron_jobs
- name: Setup Cron Jobs
  become: yes
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.file }}"
    user: "{{ item.user | default('root')}}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.dat | default('*') }}"
    weekday: "{{ item.week | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ cron_jobs | list | unique }}"
  notify: restart cron