---

- name: Ensure cron is installed
  become: yes
  apt:
    pkg: cron
    state: present
  tags:
    - cron

- name: Ensure Cron is running
  become: yes
  service:
    name: cron
    state: started
    enabled: yes
  tags:
    - cron

- include: jobs.yml
  when: cron_jobs is defined
  tags:
    - cron